### PR TITLE
UISEES-42 provide distinct permission values

### PR DESCRIPTION
**Pull request by zburke**
Translations were not synced with changes in `package.json`, leading to
the appearance of duplicate displays in the UI. In fact, only the
translation values were duplicated; the actual `permissionName` values
were distinct.

Refs [UISEES-42](https://issues.folio.org/browse/UISEES-42)

### CODE REVIEW

**Review by Dmytro-Melnyshyn — APPROVED** [review]

**Review by Godlevskyi — APPROVED** [review]

**Comment by zburke** [comment]
@Godlevskyi, @Dmytro-Melnyshyn, can we please get this merged before the release? These identically-named permissions have been confusing for our POs; they would certainly be confusing for end-users as well.

**Comment by Godlevskyi** [comment]
> @Godlevskyi, @Dmytro-Melnyshyn, can we please get this merged before the release? These identically-named permissions have been confusing for our POs; they would certainly be confusing for end-users as well.

Hi @zburke , sure we can merge it. Just looks like there is a merge conflict. Will you be able to resolve the conflict and merge it or do you want me to do it?

**Comment by zburke** [comment]
@Godlevskyi, this PR is now up to date and ready to merge. If it falls out of sync again please let me know and I'll merge master in again.

**Comment by Godlevskyi** [comment]
> @Godlevskyi, this PR is now up to date and ready to merge. If it falls out of sync again please let me know and I'll merge master in again.

Thanks @zburke 
Merged

**Pull request merged**
